# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('duracion_estimada', models.IntegerField()),
                ('tiempo', models.IntegerField()),
                ('status', models.CharField(default='pendiente', max_length=20)),
            ],
        ),
    ]
