# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_auto_20180316_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
